/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Reference design color palette
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'background': '#131313',
        'on-background': '#e5e2e1',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#bbcabf',
        'primary': '#4edea3',
        'primary-container': '#10b981',
        'primary-fixed': '#6ffbbe',
        'primary-fixed-dim': '#4edea3',
        'on-primary': '#003824',
        'on-primary-container': '#00422b',
        'on-primary-fixed': '#002113',
        'secondary': '#68dba9',
        'secondary-container': '#25a475',
        'secondary-fixed': '#85f8c4',
        'secondary-fixed-dim': '#68dba9',
        'on-secondary': '#003825',
        'on-secondary-container': '#00311f',
        'on-secondary-fixed': '#002114',
        'on-secondary-fixed-variant': '#005137',
        'tertiary': '#ffb2b7',
        'tertiary-container': '#ff7886',
        'tertiary-fixed': '#ffdadb',
        'tertiary-fixed-dim': '#ffb2b7',
        'on-tertiary': '#67001b',
        'on-tertiary-container': '#780021',
        'on-tertiary-fixed': '#40000d',
        'on-tertiary-fixed-variant': '#92002a',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'outline': '#86948a',
        'outline-variant': '#3c4a42',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'inverse-primary': '#006c49',
        'surface-tint': '#4edea3',
      },
      fontFamily: {
        'headline': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body': ['"Inter"', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['2.25rem', { lineHeight: '2.5rem', letterSpacing: '-0.025em' }],
        'headline-lg': ['1.875rem', { lineHeight: '2.25rem', letterSpacing: '-0.02em' }],
        'headline-md': ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.015em' }],
        'headline-sm': ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '-0.01em' }],
        'headline-lg-mobile': ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.015em' }],
        'headline-md-mobile': ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '-0.01em' }],
        'headline-sm-mobile': ['1.125rem', { lineHeight: '1.5rem', letterSpacing: '-0.005em' }],
        'label-lg': ['1rem', { lineHeight: '1.5rem', letterSpacing: '0.01em' }],
        'label-md': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.015em' }],
        'label-sm': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.02em' }],
        'body-lg': ['1rem', { lineHeight: '1.5rem', letterSpacing: '0.01em' }],
        'body-md': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.015em' }],
        'body-sm': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.02em' }],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
      },
    },
  },
  plugins: [],
}
